apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-auth
  namespace: monitoring
data:
  password: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA0QUM1MTZCNUcvQjA0QjIwWUdWQUwvN2VTNFFRTTZkamlDUW1kQ1VGS3lSWm1W
  # base64 encoded password
  # echo -n 'slack api url' | base64
